# Generated by Django 2.0.8 on 2018-09-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JAVATEST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUESTION_NO', models.IntegerField(default=0)),
                ('QUESTION', models.CharField(max_length=300)),
                ('OPTION1', models.CharField(max_length=300)),
                ('OPTION2', models.CharField(max_length=300)),
                ('OPTION3', models.CharField(max_length=300)),
                ('OPTION4', models.CharField(max_length=300)),
                ('ANSWER', models.IntegerField(default=0)),
            ],
        ),
    ]
