# Generated by Django 2.1.2 on 2018-11-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_result_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cstest',
            name='ANSWER',
        ),
    ]
